runtime: php73
handlers:
- url: /.*
  script: auto
env_variables:
  MYSQL_HOST: mysql:unix_socket=/cloudsql/wayang-314813:asia-southeast2:ttow
  MYSQL_DB: wayangkulit
  MYSQL_USER: root  
  MYSQL_PASS: wyg2021