runtime: php73
handlers:
- url: /.*
  script: auto
entrypoint:
  serve handler.php
env_variables:
  MYSQL_HOST: mysql:unix_socket=/cloudsql/wayang-316115:asia-southeast2:ttow
  MYSQL_DB: wayangkulit
  MYSQL_USER: root
  MYSQL_PASS: wyg2021